### ISSUE TITLE
Not supported symbols.

### ISSUE THREAD

**Issue by rutvik110** [simpleclub/CaTeX#74]
Having an error for spacing annotations and mathematical symbols annotation  binom and mathrm are not supported.I'll try to get this issue solved from my side but it will take some time.Please consider fixing them soon if possible.

**Comment by creativecreatorormaybenot** [comment]
Hi @rutvik110. Thanks for trying out the package ❤️ 

Actually, the project is on-hold at the moment (because we have some other priorities). In the meantime, you can checkout https://github.com/znjameswu/flutter_math (which we helped with). That package does support what CaTeX does not currently support.

**Comment by rutvik110** [comment]
> Hi @rutvik110. Thanks for trying out the package 
> 
> Actually, the project is on-hold at the moment (because we have some other priorities). In the meantime, you can checkout https://github.com/znjameswu/flutter_math (which we helped with). That package does support what CaTeX does not currently support.

**Comment by rutvik110** [comment]
Ok.Thanx,i'll check out the other package you mentioned.
