### ISSUE TITLE
I cannot find the document for the available macros and syntaxes

### ISSUE THREAD

**Issue by ComputelessComputer** [simpleclub/CaTeX#80]
## Feature description

@creativecreatorormaybenot  Is there a document where I can find the available syntaxes and macros for CaTeX?

Right now I am having some troubles with finding the necessary syntaxes so I would appreciate with some clear reference :)

**Comment by creativecreatorormaybenot** [comment]
Hi @ComputelessComputer :) Thanks for asking.

We have a file at https://github.com/simpleclub/CaTeX/blob/master/function_prioritization.csv, which does show which functions we support in CaTeX.

We have not worked on CaTeX itself since the pre-release version, which is why support is still very limited (on-hold for now) 🙂 Generally, the expected support would be what you can find at https://katex.org/docs/supported.html.

However, we have collaborated on [`flutter_math`](https://pub.dev/packages/flutter_math), which works similarly and **does support** a lot of the functions already :)

Let me know if this helped you 👌

**Comment by ComputelessComputer** [comment]
Thanks, I 'll be sure to check it out and get back to you asap
